language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - cp .env.example .env

script:
  - vendor/bin/phpunit --exclude-group integration --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
